# Generated by Django 5.1.5 on 2025-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_newsletterform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterForm',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', width_field=200),
        ),
    ]
