# Generated by Django 5.1.5 on 2025-02-05 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityPost',
            new_name='ForumPost',
        ),
    ]
