# Generated by Django 5.1.5 on 2025-02-06 03:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0004_rename_comment_forumcomment_forumlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='post',
            new_name='fpost',
        ),
        migrations.RenameField(
            model_name='forumlike',
            old_name='post',
            new_name='fpost',
        ),
        migrations.AlterUniqueTogether(
            name='forumlike',
            unique_together={('user', 'fpost')},
        ),
    ]
