# Generated by Django 5.1.5 on 2025-02-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0005_rename_post_forumcomment_fpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='briskbrick.forumcomment'),
        ),
    ]
