# Generated by Django 5.1.5 on 2025-02-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0006_forumcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
