# Generated by Django 5.1.5 on 2025-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0007_alter_goal_deadline_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
