# Generated by Django 5.1.5 on 2025-02-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0008_alter_goal_deadline_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('In Progress', 'in_progress'), ('completed', 'Completed'), ('On Hold', 'on_hold')], default='In Progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Not Urgent', 'not_urgent'), ('Not Important', 'not_important'), ('Urgent', 'urgent'), ('Important', 'important'), ('Both', 'both')], default='Not Urgent', max_length=30),
        ),
    ]
