# Generated by Django 5.1.5 on 2025-02-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0009_alter_goal_status_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending'), ('on_hold', 'On Hold')], default='pending', max_length=30),
        ),
    ]
