# Generated by Django 5.1.5 on 2025-02-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0010_alter_goal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('not_urgent', 'Not Urgent'), ('not_important', 'Not Important'), ('urgent', 'Urgent'), ('important', 'Important'), ('both', 'Both')], default='Not Urgent', max_length=30),
        ),
    ]
