# Generated by Django 5.1.5 on 2025-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0011_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
