# Generated by Django 5.1.5 on 2025-02-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0012_forumpost_is_anonymous_alter_goal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_media',
            field=models.FileField(blank=True, null=True, upload_to='task/progress/'),
        ),
    ]
