# Generated by Django 5.1.5 on 2025-02-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briskbrick', '0015_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
